#!/bin/sh
# runner.sh — 一键安装本仓库的 tmux / vim 配置
#
# 用法:
#   git clone https://github.com/zhuge2580787500/tmux-vim_conf.git
#   cd tmux-vim_conf && sh runner.sh            # 装到当前账号 (~)
#                        sudo sh runner.sh -s   # 装到系统级 /etc, 全服务器用户生效
#
# 以"拷贝"方式安装: 配置文件复制到 home / etc 后, 本仓库文件夹即可删除,
# 配置不受影响。已存在的配置会先备份为 *.bak.<时间戳>。
set -eu

# 判断 Debian/Ubuntu 家族(系统 vimrc 路径和加载方式不同)
is_debian_family() {
  [ -x /usr/bin/dpkg ] && command -v apt-get >/dev/null 2>&1
}

usage() {
  echo "用法: $0 [-s]" >&2
  echo "  (无参数)  安装到当前账号 ~ 目录" >&2
  echo "  -s        安装到系统级 /etc 目录 (需 root)" >&2
  exit 1
}

# --- 解析参数 ---
system_mode=0
while [ $# -gt 0 ]; do
  case "$1" in
    -s|--system) system_mode=1 ;;
    -h|--help) usage ;;
    *) echo "未知参数: $1" >&2; usage ;;
  esac
  shift
done

# --- 1. 定位仓库根目录(脚本所在目录), 任意位置调用都可靠 ---
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$SCRIPT_DIR"

# --- 2. 检查依赖, 缺了只警告不中断 ---
for cmd in tmux vim; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "警告: 未找到命令 '$cmd', 请先安装 (apt install $cmd / yum install $cmd)" >&2
  fi
done

# --- 3. 备份旧文件: 普通文件备份; 旧软链接直接移除(不影响它指向的原文件) ---
backup_if_exists() {
  dst=$1
  if [ -L "$dst" ]; then
    rm -f "$dst"
    echo "  已移除旧软链接: $dst"
  elif [ -e "$dst" ]; then
    cp "$dst" "$dst.bak.$(date +%Y%m%d%H%M%S)"
    echo "  已备份旧配置: $dst"
  fi
}

copy_file() {
  src=$1; dst=$2
  backup_if_exists "$dst"
  cp "$src" "$dst"
  echo "  已安装: $dst"
}

# --- 4. 按模式安装 ---
if [ "$system_mode" = "1" ]; then
  echo ">> 系统级安装 (需 root):"
  mkdir -p /etc/vim/colors

  copy_file .tmux.conf /etc/tmux.conf
  copy_file colors/molokai.vim /etc/vim/colors/molokai.vim

  # Debian/Ubuntu 加载 /etc/vim/vimrc.local; 其它发行版直接 /etc/vimrc
  if is_debian_family; then
    VIMRC_DST=/etc/vim/vimrc.local
  else
    VIMRC_DST=/etc/vimrc
  fi
  backup_if_exists "$VIMRC_DST"
  # 前面加一行 runtimepath, 保证 vim 能找到 /etc/vim/colors 里的 molokai 配色
  {
    echo "\" generated by runner.sh -s"
    echo "set runtimepath+=/etc/vim"
    echo
    cat .vimrc
  } > "$VIMRC_DST"
  echo "  已安装: $VIMRC_DST"
else
  echo ">> 用户级安装:"
  copy_file .tmux.conf "$HOME/.tmux.conf"
  copy_file .vimrc "$HOME/.vimrc"
  mkdir -p "$HOME/.vim/colors"
  copy_file colors/molokai.vim "$HOME/.vim/colors/molokai.vim"
fi

echo
echo "完成! 重新打开 tmux / vim 即可生效。"
echo "现在可以删除本仓库文件夹, 配置已独立拷贝到上述位置。"