#!/bin/sh
# runner.sh — 一键安装本仓库的 tmux / vim 配置
#
# 用法:
#   git clone https://github.com/zhuge2580787500/tmux-vim_conf.git
#   cd tmux-vim_conf && sh runner.sh            # 装到当前用户 (~)
#   sudo sh runner.sh -s                        # 装到系统级 (/etc/...), 全服务器用户生效
#
# 安装位置:
#   用户级 (推荐): ~/.tmux.conf  ~/.vimrc  ~/.vim/colors/molokai.vim
#   系统级:       /etc/tmux.conf  /etc/vim/vimrc.local 或 /etc/vimrc  /etc/vim/colors/
#
# 特性:
#   * 用软链接指向本仓库文件, 仓库里 git pull 后配置自动同步更新
#   * 已存在的非软链接配置会先备份为 *.bak.<时间戳>, 不会覆盖
set -eu

# 判断 Debian/Ubuntu 家族(它们的系统 vimrc 路径和加载方式不同)
is_debian_family() {
  [ -x /usr/bin/dpkg ] && command -v apt-get >/dev/null 2>&1
}

usage() {
  echo "用法: $0 [-s]" >&2
  echo "  (无参数)  安装到当前账号 ~ 目录" >&2
  echo "  -s        安装到系统级 /etc 目录 (需 root)" >&2
  exit 1
}

# --- 解析参数 ---
system_mode=0
while [ $# -gt 0 ]; do
  case "$1" in
    -s|--system) system_mode=1 ;;
    -h|--help) usage ;;
    *) echo "未知参数: $1" >&2; usage ;;
  esac
  shift
done

# --- 1. 定位仓库根目录(脚本所在目录), 任意位置调用都可靠 ---
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$SCRIPT_DIR"

# --- 2. 检查依赖, 缺了只警告不中断 ---
for cmd in tmux vim; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "警告: 未找到命令 '$cmd', 请先安装 (apt install $cmd / yum install $cmd)" >&2
  fi
done

# --- 3. 工具函数: 备份旧文件 / 建软链接 ---
backup_if_exists() {
  dst=$1
  if [ -e "$dst" ] && [ ! -L "$dst" ]; then
    cp "$dst" "$dst.bak.$(date +%Y%m%d%H%M%S)"
    echo "  已备份旧配置: $dst"
  fi
}

install_symlink() {
  src=$1; dst=$2
  backup_if_exists "$dst"
  ln -sfn "$SCRIPT_DIR/$src" "$dst"
  echo "  已安装: $dst"
}

# --- 4. 按模式安装 ---
if [ "$system_mode" = "1" ]; then
  echo ">> 系统级安装 (需 root):"
  TMUX_DST=/etc/tmux.conf
  VIM_COLORS_DIR=/etc/vim/colors
  mkdir -p "$VIM_COLORS_DIR"

  install_symlink .tmux.conf "$TMUX_DST"
  install_symlink colors/molokai.vim "$VIM_COLORS_DIR/molokai.vim"

  # Debian 家族: 系统会加载 /etc/vim/vimrc.local, 不覆盖原有系统 vimrc
  # 其它发行版: 直接使用 /etc/vimrc
  if is_debian_family; then
    VIMRC_DST=/etc/vim/vimrc.local
  else
    VIMRC_DST=/etc/vimrc
  fi
  backup_if_exists "$VIMRC_DST"
  # 写一个包装 vimrc: 把 /etc/vim 加进 runtimepath(否则非 Debian 找不到配色),
  # 再加载仓库里的 .vimrc
  {
    echo "\" generated by runner.sh -s"
    echo "set runtimepath+=/etc/vim"
    echo "if filereadable('$SCRIPT_DIR/.vimrc')"
    echo "  source $SCRIPT_DIR/.vimrc"
    echo "endif"
  } > "$VIMRC_DST"
  echo "  已安装: $VIMRC_DST"
else
  echo ">> 用户级安装:"
  install_symlink .tmux.conf "$HOME/.tmux.conf"
  install_symlink .vimrc "$HOME/.vimrc"
  mkdir -p "$HOME/.vim/colors"
  install_symlink colors/molokai.vim "$HOME/.vim/colors/molokai.vim"
fi

echo
echo "完成! 重新打开 tmux / vim 即可生效。"
echo "之后在仓库目录执行 git pull 可同步更新配置。"